%YAML 1.1
---
$schema: asdf://stsci.edu/datamodels/roman/schemas/rad_schema-1.0.0
id: asdf://stsci.edu/datamodels/roman/schemas/meta/product_type-1.0.0

title: Product Type Descriptor
description: |
  A descriptor for the type of data contained within the
  file. This corresponds to the standard file suffixes for
  archival data products. Consult the documentation for the list
  of options. A string beginning with "p" indicates a prompt data
  product, while a string beginning with "r" indicates a data release
  product.  For example, "p_visit_coadd" indicates a prompt data
  product containing a co-addition of exposures within a visit.
type: string
maxLength: 120
sdf:
  special_processing: VALUE_REQUIRED
  source:
    origin: TBD
archive_catalog:
  datatype: nvarchar(120)
  destination:
    [
      WFIExposure.product_type,
      GuideWindow.product_type,
      WFICommon.product_type,
      WFIMosaic.product_type,
      SourceCatalog.product_type,
      SegmentationMap.product_type,
    ]
