%YAML 1.1
---
$schema: asdf://stsci.edu/datamodels/roman/schemas/rad_schema-1.0.0
id: asdf://stsci.edu/datamodels/roman/schemas/tagged_scalars/product_type-1.0.0

title: Product Type Descriptor
type: string
sdf:
  special_processing: VALUE_REQUIRED
  source:
    origin: TBD
maxLength: 120
archive_catalog:
  datatype: nvarchar(120)
  destination: [WFIExposure.product_type, GuideWindow.product_type,
                WFICommon.product_type, WFIMosaic.product_type,
                SourceCatalog.product_type, SegmentationMap.product_type]

flowStyle: block
...
