name: tests

on:
  push:
    branches:
      - main
      - "*"
    tags:
      - "*"
  pull_request:
  schedule:
    # Weekly Monday 9AM build
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@8c8bb6c6c962542921f993d47d26df38dccd50b1 # v3.0.2
    with:
      envs: |
        - linux: py311-xdist
        - linux: py312-xdist
        - linux: py313-xdist
        - linux: py314-cov-xdist
          coverage: codecov
        - macos: py314-xdist
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  roman_datamodels:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@8c8bb6c6c962542921f993d47d26df38dccd50b1 # v3.0.2
    with:
      envs: |
        - linux: roman_datamodels-xdist

  romancal:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@8c8bb6c6c962542921f993d47d26df38dccd50b1 # v3.0.2
    with:
      envs: |
        - linux: py313-romancal
